### ISSUE TITLE
New contributers

### ISSUE THREAD

**Issue by RoelofSol** [wkmeijer/CS4160-trustchain-android#55]
Heej , 

[We](https://github.com/Tribler/tribler/issues/3239) ran into some trouble with the app, and since we heard another team was working on similar issues @synctext suggested we start having some inter team communication in general about what our objectives and ambitions are and asses how feasible it is to work on a common code base ( that will still be maintained after this quarter ). 

So @wkmeijer and @klikooo, can one of you spare 30 min in the next week to talk in person and catch us up on the state of the project and discuss some of the possibilities ?

**Comment by klikooo** [comment]
After the lecture on Tuesday we have time for you. So could you come to us after the lecture?

**Comment by RoelofSol** [comment]
Cool, we will.
