### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by klikooo** [wkmeijer/CS4160-trustchain-android#9]
Connect with another phone via IP and using google protocol buffers

**Comment by wkmeijer** [comment]
https://developer.android.com/reference/java/net/ServerSocket.html

**Comment by wkmeijer** [comment]
[Connecting two phones via the mobile network might be an issue. ](https://stackoverflow.com/questions/6748435/android-client-pc-server-socket-dont-work-over-3g)
So I guess we have to use methods that require the devices to be nearby.

**Comment by wkmeijer** [comment]
For protocolbuffers see:
- https://developers.google.com/protocol-buffers/docs/javatutorial
- https://github.com/jgilfelt/android-protobuf-example
